In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
from src.data_loader import load_train_data, load_test_data

train_df = load_train_data()
test_df = load_test_data()

print(train_df.shape)
print(test_df.shape)

(175341, 36)
(82332, 36)

In [3]:
from src.model_loader import load_random_forest, load_label_encoders

rf = load_random_forest()
encoders = load_label_encoders()

print(type(rf))
print(type(encoders))
print(encoders.keys())

d:\ASR\Anomaly Detection System\.venv\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.6.1 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

<class 'sklearn.ensemble._forest.RandomForestClassifier'>
<class 'dict'>
dict_keys(['proto', 'service', 'state'])

d:\ASR\Anomaly Detection System\.venv\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator RandomForestClassifier from version 1.6.1 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
d:\ASR\Anomaly Detection System\.venv\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator LabelEncoder from version 1.6.1 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [4]:
from src.preprocessing import prepare_features, encode_features
from src.model_loader import load_scaler

# Load the scaler alongside encoders
scaler = load_scaler()

X_test, y_test = prepare_features(test_df)
# Pass the scaler to encode_features
X_test = encode_features(X_test, encoders, scaler=scaler)

print(X_test.shape)
print(y_test.shape)

(82332, 34)
(82332,)

d:\ASR\Anomaly Detection System\.venv\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.6.1 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [5]:
from src.data_loader import load_test_data
from src.model_loader import load_random_forest, load_label_encoders
from src.preprocessing import prepare_features, encode_features

In [6]:
from src.inference import (
    predict,
    predict_probability,
    predict_batch,
    predict_sample
)

In [7]:
predictions = predict(rf, X_test)

print(predictions[:10])

[1 1 1 1 1 1 0 1 0 0]

In [8]:
probabilities = predict_probability(rf, X_test)

print(probabilities[:10])

[0.94       0.91       0.53512208 0.62785714 0.67116667 0.89846154
 0.41       0.77       0.         0.        ]

In [9]:
results = predict_batch(rf, X_test)

results.head()

   prediction  probability
0           1     0.940000
1           1     0.910000
2           1     0.535122
3           1     0.627857
4           1     0.671167

In [10]:
print(X_test.shape)

(82332, 34)

In [11]:
X_test.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,smean,dmean,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports
0,-0.209773,0.420235,-0.702307,0.742936,-0.133677,-0.172047,-0.047772,-0.103923,-0.027189,0.567591,...,0.543531,-0.480703,-0.136415,-0.039557,-0.544736,-0.554373,-0.11859,-0.11859,-0.189768,-0.126508
1,-0.209774,0.420235,-0.702307,0.742936,-0.133677,-0.172047,-0.040528,-0.103923,0.178922,4.287318,...,3.636212,-0.480703,-0.136415,-0.039557,-0.544736,-0.554373,-0.11859,-0.11859,-0.189768,-0.126508
2,-0.209774,0.420235,-0.702307,0.742936,-0.133677,-0.172047,-0.044499,-0.103923,0.632367,4.146097,...,1.940856,-0.480703,-0.136415,-0.039557,-0.544736,-0.554373,-0.11859,-0.11859,-0.189768,-0.126508
3,-0.209774,0.420235,-0.702307,0.742936,-0.133677,-0.172047,-0.045460,-0.103923,0.430836,2.795469,...,1.530453,-0.480703,-0.136415,-0.039557,-0.420468,-0.554373,-0.11859,-0.11859,-0.189768,-0.126508
4,-0.209773,0.420235,-0.702307,0.742936,-0.133677,-0.172047,-0.038445,-0.103923,0.027774,4.124860,...,4.525419,-0.480703,-0.136415,-0.039557,-0.420468,-0.554373,-0.11859,-0.11859,-0.189768,-0.126508

In [12]:
print(X_test.columns.tolist())

['dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sload', 'dload', 'sloss', 'dloss', 'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth', 'response_body_len', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'is_sm_ips_ports']

In [13]:
probs = rf.predict_proba(X_test)

print(probs[:10])

d:\ASR\Anomaly Detection System\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

[[0.06       0.94      ]
 [0.09       0.91      ]
 [0.46487792 0.53512208]
 [0.37214286 0.62785714]
 [0.32883333 0.67116667]
 [0.10153846 0.89846154]
 [0.59       0.41      ]
 [0.23       0.77      ]
 [1.         0.        ]
 [1.         0.        ]]

In [14]:
print(X_test.shape)
print(rf.n_features_in_)

(82332, 34)
34

In [15]:
X_test.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sload,...,smean,dmean,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports
0,-0.209773,0.420235,-0.702307,0.742936,-0.133677,-0.172047,-0.047772,-0.103923,-0.027189,0.567591,...,0.543531,-0.480703,-0.136415,-0.039557,-0.544736,-0.554373,-0.11859,-0.11859,-0.189768,-0.126508
1,-0.209774,0.420235,-0.702307,0.742936,-0.133677,-0.172047,-0.040528,-0.103923,0.178922,4.287318,...,3.636212,-0.480703,-0.136415,-0.039557,-0.544736,-0.554373,-0.11859,-0.11859,-0.189768,-0.126508
2,-0.209774,0.420235,-0.702307,0.742936,-0.133677,-0.172047,-0.044499,-0.103923,0.632367,4.146097,...,1.940856,-0.480703,-0.136415,-0.039557,-0.544736,-0.554373,-0.11859,-0.11859,-0.189768,-0.126508
3,-0.209774,0.420235,-0.702307,0.742936,-0.133677,-0.172047,-0.045460,-0.103923,0.430836,2.795469,...,1.530453,-0.480703,-0.136415,-0.039557,-0.420468,-0.554373,-0.11859,-0.11859,-0.189768,-0.126508
4,-0.209773,0.420235,-0.702307,0.742936,-0.133677,-0.172047,-0.038445,-0.103923,0.027774,4.124860,...,4.525419,-0.480703,-0.136415,-0.039557,-0.420468,-0.554373,-0.11859,-0.11859,-0.189768,-0.126508

In [16]:
X_test.iloc[:5].nunique()

dur                  5
proto                1
service              1
state                1
spkts                1
dpkts                1
sbytes               5
dbytes               1
rate                 5
sload                5
dload                1
sloss                1
dloss                1
sinpkt               5
dinpkt               1
sjit                 1
djit                 1
swin                 1
stcpb                1
dtcpb                1
dwin                 1
tcprtt               1
synack               1
ackdat               1
smean                5
dmean                1
trans_depth          1
response_body_len    1
ct_src_dport_ltm     2
ct_dst_sport_ltm     1
is_ftp_login         1
ct_ftp_cmd           1
ct_flw_http_mthd     1
is_sm_ips_ports      1
dtype: int64

In [17]:
print(rf)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [18]:
print(rf.get_params())

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 100, 'n_jobs': -1, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}

In [19]:
from sklearn.metrics import accuracy_score

pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

d:\ASR\Anomaly Detection System\.venv\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

Accuracy: 0.8691031433707428

In [20]:
from src.risk_engine import build_risk_assessment

assessment = build_risk_assessment(
    prediction=1,
    probability=0.94
)

assessment

{'prediction': 'Attack',
 'probability': 0.94,
 'risk_score': 94,
 'severity': 'Critical',
 'priority': 'P1',
 'recommendation': 'Immediately isolate the affected host and begin incident response.'}

In [21]:
results = predict_batch(rf, X_test)

assessments = []

for _, row in results.head(10).iterrows():
    assessments.append(
        build_risk_assessment(
            prediction=row["prediction"],
            probability=row["probability"]
        )
    )

assessments

[{'prediction': 'Attack',
  'probability': 0.94,
  'risk_score': 94,
  'severity': 'Critical',
  'priority': 'P1',
  'recommendation': 'Immediately isolate the affected host and begin incident response.'},
 {'prediction': 'Attack',
  'probability': 0.91,
  'risk_score': 91,
  'severity': 'Critical',
  'priority': 'P1',
  'recommendation': 'Immediately isolate the affected host and begin incident response.'},
 {'prediction': 'Attack',
  'probability': 0.5351,
  'risk_score': 54,
  'severity': 'High',
  'priority': 'P2',
  'recommendation': 'Investigate the endpoint and validate suspicious activity.'},
 {'prediction': 'Attack',
  'probability': 0.6279,
  'risk_score': 63,
  'severity': 'High',
  'priority': 'P2',
  'recommendation': 'Investigate the endpoint and validate suspicious activity.'},
 {'prediction': 'Attack',
  'probability': 0.6712,
  'risk_score': 67,
  'severity': 'High',
  'priority': 'P2',
  'recommendation': 'Investigate the endpoint and validate suspicious activity.'},
 {'prediction': 'Attack',
  'probability': 0.8985,
  'risk_score': 90,
  'severity': 'Critical',
  'priority': 'P1',
  'recommendation': 'Immediately isolate the affected host and begin incident response.'},
 {'prediction': 'Normal',
  'probability': 0.41,
  'risk_score': 41,
  'severity': 'Medium',
  'priority': 'P3',
  'recommendation': 'Review logs and verify network behavior.'},
 {'prediction': 'Attack',
  'probability': 0.77,
  'risk_score': 77,
  'severity': 'Critical',
  'priority': 'P1',
  'recommendation': 'Immediately isolate the affected host and begin incident response.'},
 {'prediction': 'Normal',
  'probability': 0.0,
  'risk_score': 0,
  'severity': 'Low',
  'priority': 'P4',
  'recommendation': 'Monitor the connection for unusual activity.'},
 {'prediction': 'Normal',
  'probability': 0.0,
  'risk_score': 0,
  'severity': 'Low',
  'priority': 'P4',
  'recommendation': 'Monitor the connection for unusual activity.'}]

In [24]:
from src.alert_engine import build_alert

assessment = build_risk_assessment(
    prediction=1,
    probability=0.94
)

alert = build_alert(assessment)

alert

{'alert_id': 'ALT-B957E3F7',
 'timestamp': '2026-06-28T13:11:24.539525+00:00',
 'status': 'Open',
 'prediction': 'Attack',
 'probability': 0.94,
 'risk_score': 94,
 'severity': 'Critical',
 'priority': 'P1',
 'recommendation': 'Immediately isolate the affected host and begin incident response.'}